blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name="posts"), 
    path("<int:post_id>", post_detail, name="post_detail"),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Para que se carguen las imagenes

blog/models.py
from django.db import models

import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images/")
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts': posts})
 

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    project = Project.objects.all()

    return render(request, 'home.html', {'project': project})

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<h1>Post</h1>

{% for post in posts  %}

<section class="p-5">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
        
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description |striptags|truncatechars:100}}</p>
                <p>{{post.date|date:'M d Y'|upper}}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div
    </div>
</section>   

{% endfor %}

{% endblock content %}

blog/templates/post_detail.html
{% extends 'layout.html' %}


{% block content %}

<section class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date |date:'F jS Y'}}</h3>
    
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">

    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>
</section>
    
{% endblock content %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black" >
    <div class="col-md-4">
        <img src="{% static 'portfolio/python.png'%}" alt="Es una imagen de mi perfil">
    </div>

    <div class="col-md-8 my-auto">
        <h1>I am Leiber Bertel</h1>
        <h3>I am Python FullStack Developer</h3>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum ipsa consectetur, odio quae, eveniet reprehenderit porro optio ratione delectus cupiditate at quod voluptas animi iste tenetur? Hic, aliquid cupiditate aliquam ipsam omnis at aperiam? Consequatur repellendus id assumenda, aliquam fugiat incidunt, eaque reiciendis natus accusantium dolor ratione commodi laudantium reprehenderit dolores modi animi magni harum tempora. Tempore possimus dicta odit sed culpa optio nulla vero nobis illo, eos voluptas natus, voluptatem ducimus blanditiis dolores illum perferendis assumenda nesciunt animi molestias cum minima vitae! Quo commodi autem laudantium aperiam, fugiat cum odio repellendus repudiandae amet sapiente quaerat, enim rerum ut doloremque?
        </p>

        <a href="{% static 'portfolio/diploma-python-profesional.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">Descargar Cv</a>
            
    </div>
</header>

<section class="row my-4 text-center" >
    <h3>Mis proyectos</h3>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Totam, excepturi.</p>
</section>


{% for project in project %}

<div class="col-md-4 p-4">
    <div class="card bg-black card-project">
        <img src="{{project.image.url}}" 
             alt="{{ project.title }}" 
             class="card-img-top" >
        
            <div class="card-body">
            <h2>{{ project.title }}</h2> 
            <p>{{ project.description }}</p>

            {% if project.url %}
            <a href="{{ project.url }}" 
               class="btn btn-light row-0 btn-sm" 
               target="_blank">{{ project.url }}</a>
            {% endif %}
        </div>
    </div>
</div>

{% endfor %}

{% endblock content %}

portfolio/templates/index.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black" >
    <div class="col-md-4">
        <img src="{% static 'portfolio/python.png'%}" alt="Es una imagen de mi perfil">
    </div>

    <div class="col-md-8 my-auto">
        <h1>I am Leiber Bertel</h1>
        <h3>I am Python FullStack Developer</h3>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum ipsa consectetur, odio quae, eveniet reprehenderit porro optio ratione delectus cupiditate at quod voluptas animi iste tenetur? Hic, aliquid cupiditate aliquam ipsam omnis at aperiam? Consequatur repellendus id assumenda, aliquam fugiat incidunt, eaque reiciendis natus accusantium dolor ratione commodi laudantium reprehenderit dolores modi animi magni harum tempora. Tempore possimus dicta odit sed culpa optio nulla vero nobis illo, eos voluptas natus, voluptatem ducimus blanditiis dolores illum perferendis assumenda nesciunt animi molestias cum minima vitae! Quo commodi autem laudantium aperiam, fugiat cum odio repellendus repudiandae amet sapiente quaerat, enim rerum ut doloremque?
        </p>

        <a href="{% static 'portfolio/diploma-python-profesional.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">Descargar Cv</a>
            
    </div>
</header>

<section class="row my-4 text-center" >
    <h3>Mis proyectos</h3>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Totam, excepturi.</p>
</section>


{% for project in project %}

<div class="col-md-4 p-4">
    <div class="card bg-black card-project">
        <img src="{{project.image.url}}" 
             alt="{{ project.title }}" 
             class="card-img-top" >
        
            <div class="card-body">
            <h2>{{ project.title }}</h2> 
            <p>{{ project.description }}</p>

            {% if project.url %}
            <a href="{{ project.url }}" 
               class="btn btn-light row-0 btn-sm" 
               target="_blank">{{ project.url }}</a>
            {% endif %}
        </div>
    </div>
</div>

{% endfor %}

{% endblock content %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Django Portfolio</title>
</head>
<body class="text-light">

    {% include 'partials/_navbar.html' %}
    
    <section class="container p-4">
        {% block content %}
        {% endblock content %}
    </section>

    <footer class="text-center h6">Hecho con 💚 por Leiber Bertel</footer>

</body>
</html>

portfolio/templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Leiber Bertel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center ">
            <a class="btn btn-primary btn-sm" 
              href="{% static 'portfolio/diploma-python-profesional.pdf' %}" 
              target='_blank'>Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>